server:
  port: 8080

spring:
  application:
    name: cargo-pulse-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cargopulse}
    username: ${SPRING_DATASOURCE_USERNAME:cargopulse}
    password: ${SPRING_DATASOURCE_PASSWORD:cargopulse}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info

cargopulse:
  kafka-topic: ${KAFKA_TOPIC:shipment-events}
